---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ghzplugi/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp aso.png $DEPLOYPATH
    - /bin/cp donestok.png $DEPLOYPATH
    - /bin/cp excel.png $DEPLOYPATH
    - /bin/cp studioflow.png $DEPLOYPATH
